// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aflvkrtwkusjoqdtkfuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmbHZrcnR3a3Vzam9xZHRrZnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTE1NjAsImV4cCI6MjA3NDI4NzU2MH0.mhcuJiXedyOf_8WEmZk7R7prlNJbHr6_X4_1ou7gdk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});